### ISSUE TITLE
play icon not responding to system playback controls

### ISSUE THREAD

**Issue by waymondrang** [chiyeon/jukebox#1]
pausing the music externally (from the system) does not change the play icon to pause state. in the image below, the current playback state is paused, even though the icon indicates it as playing.

<img width="866" alt="image" src="https://github.com/chiyeon/jukebox/assets/57642450/7235206d-3a5d-4784-a70b-d12fd6ce5c33">

**Comment by waymondrang** [comment]
i would like to clarify this is not an issue with the pausing of music itself, only the visual indication reflecting the current playback state.

**Comment by chiyeon** [comment]
Thank you for pointing this issue out! We were using an unnecessary variable to track the play state of the HTML audio element when we could have used the built in `pause` attribute.
